import sys
import cv2
import numpy as np


# ============================================================
# DRIFT-SENSE V5.2
# SPATIALLY-AWARE CANDIDATE RERANKING
# ============================================================

TEMPLATE_SIZE = 100

# Number of candidates generated by template matching
TOP_K = 30

# Larger context used for neighborhood verification
CONTEXT_SIZE = 300

# V5 score weights
GRAY_WEIGHT = 0.45
EDGE_WEIGHT = 0.20
GRADIENT_WEIGHT = 0.35

# Neighborhood contribution
NEIGHBOR_WEIGHT = 0.25

# Final score:
#
# final = V5_score * (1 - NEIGHBOR_WEIGHT)
#         + neighborhood_score * NEIGHBOR_WEIGHT
#
# This keeps V5 as the main signal while adding
# spatial/context information.


# ============================================================
# IMAGE FEATURES
# ============================================================

def make_edges(image):

    return cv2.Canny(
        image,
        50,
        150
    )


def make_gradient(image):

    gx = cv2.Sobel(
        image,
        cv2.CV_32F,
        1,
        0,
        ksize=3
    )

    gy = cv2.Sobel(
        image,
        cv2.CV_32F,
        0,
        1,
        ksize=3
    )

    magnitude = cv2.magnitude(
        gx,
        gy
    )

    magnitude = cv2.normalize(
        magnitude,
        None,
        0,
        255,
        cv2.NORM_MINMAX
    )

    return magnitude.astype(
        np.uint8
    )


# ============================================================
# NORMALIZED CORRELATION
# ============================================================

def correlation(template, patch):

    if template.shape != patch.shape:

        return -1.0

    template_f = (
        template.astype(
            np.float32
        )
    )

    patch_f = (
        patch.astype(
            np.float32
        )
    )

    template_f -= np.mean(
        template_f
    )

    patch_f -= np.mean(
        patch_f
    )

    denominator = (
        np.linalg.norm(template_f)
        *
        np.linalg.norm(patch_f)
    )

    if denominator < 1e-8:

        return 0.0

    value = (
        np.sum(
            template_f * patch_f
        )
        /
        denominator
    )

    return float(
        np.clip(
            value,
            -1.0,
            1.0
        )
    )


# ============================================================
# TOP CANDIDATES
# ============================================================

def get_top_candidates(
    response,
    top_k=TOP_K
):

    candidates = []

    kernel_size = 25

    kernel = np.ones(
        (
            kernel_size,
            kernel_size
        ),
        np.uint8
    )

    local_max = cv2.dilate(
        response,
        kernel
    )

    mask = (
        response >=
        local_max - 1e-6
    )

    ys, xs = np.where(
        mask
    )

    points = []

    for y, x in zip(ys, xs):

        points.append(
            (
                float(response[y, x]),
                int(x),
                int(y)
            )
        )

    points.sort(
        key=lambda item: item[0],
        reverse=True
    )

    for score, x, y in points:

        # Keep candidates spatially separated.
        too_close = False

        for _, old_x, old_y in candidates:

            distance = np.sqrt(
                (x - old_x) ** 2
                +
                (y - old_y) ** 2
            )

            if distance < 25:

                too_close = True
                break

        if too_close:
            continue

        candidates.append(
            (
                score,
                x,
                y
            )
        )

        if len(candidates) >= top_k:
            break

    return candidates


# ============================================================
# PATCH EXTRACTION
# ============================================================

def extract_center_patch(
    image,
    center_x,
    center_y,
    size
):

    half = size // 2

    x1 = int(
        round(center_x)
        - half
    )

    y1 = int(
        round(center_y)
        - half
    )

    x2 = x1 + size
    y2 = y1 + size

    if (
        x1 < 0
        or y1 < 0
        or x2 > image.shape[1]
        or y2 > image.shape[0]
    ):

        return None

    return image[
        y1:y2,
        x1:x2
    ]


# ============================================================
# NEIGHBORHOOD SCORE
# ============================================================

def neighborhood_score(
    reference,
    search,
    center_x,
    center_y
):

    # Reference context is centered at the
    # center of the reference image.

    ref_center_x = (
        reference.shape[1] / 2.0
    )

    ref_center_y = (
        reference.shape[0] / 2.0
    )

    reference_patch = extract_center_patch(
        reference,
        ref_center_x,
        ref_center_y,
        CONTEXT_SIZE
    )

    search_patch = extract_center_patch(
        search,
        center_x,
        center_y,
        CONTEXT_SIZE
    )

    if (
        reference_patch is None
        or
        search_patch is None
    ):

        return 0.0

    # Resize reference context if required.
    if (
        reference_patch.shape
        != search_patch.shape
    ):

        reference_patch = cv2.resize(
            reference_patch,
            (
                search_patch.shape[1],
                search_patch.shape[0]
            ),
            interpolation=cv2.INTER_AREA
        )

    # --------------------------------------------------------
    # Gray context similarity
    # --------------------------------------------------------

    gray_score = (
        correlation(
            reference_patch,
            search_patch
        )
    )

    gray_score = (
        gray_score + 1.0
    ) / 2.0

    # --------------------------------------------------------
    # Edge context similarity
    # --------------------------------------------------------

    ref_edges = make_edges(
        reference_patch
    )

    search_edges = make_edges(
        search_patch
    )

    edge_score = (
        correlation(
            ref_edges,
            search_edges
        )
    )

    edge_score = (
        edge_score + 1.0
    ) / 2.0

    # --------------------------------------------------------
    # Gradient context similarity
    # --------------------------------------------------------

    ref_gradient = make_gradient(
        reference_patch
    )

    search_gradient = make_gradient(
        search_patch
    )

    gradient_score = (
        correlation(
            ref_gradient,
            search_gradient
        )
    )

    gradient_score = (
        gradient_score + 1.0
    ) / 2.0

    # --------------------------------------------------------
    # Combined neighborhood score
    # --------------------------------------------------------

    score = (
        0.40 * gray_score
        +
        0.20 * edge_score
        +
        0.40 * gradient_score
    )

    return float(
        np.clip(
            score,
            0.0,
            1.0
        )
    )


# ============================================================
# V5.2 LOCAL CANDIDATE SCORE
# ============================================================

def evaluate_candidate(
    reference,
    search,
    template,
    template_edges,
    template_gradient,
    x,
    y,
    gray_score
):

    center_x = (
        x + TEMPLATE_SIZE / 2.0
    )

    center_y = (
        y + TEMPLATE_SIZE / 2.0
    )

    # --------------------------------------------------------
    # Extract 100x100 candidate
    # --------------------------------------------------------

    patch = search[
        y:y + TEMPLATE_SIZE,
        x:x + TEMPLATE_SIZE
    ]

    if (
        patch.shape
        != template.shape
    ):

        return None

    # --------------------------------------------------------
    # Edge score
    # --------------------------------------------------------

    patch_edges = make_edges(
        patch
    )

    edge_score = correlation(
        template_edges,
        patch_edges
    )

    edge_score = (
        edge_score + 1.0
    ) / 2.0

    # --------------------------------------------------------
    # Gradient score
    # --------------------------------------------------------

    patch_gradient = make_gradient(
        patch
    )

    gradient_score = correlation(
        template_gradient,
        patch_gradient
    )

    gradient_score = (
        gradient_score + 1.0
    ) / 2.0

    # --------------------------------------------------------
    # Original V5 combined score
    # --------------------------------------------------------

    v5_score = (
        GRAY_WEIGHT * gray_score
        +
        EDGE_WEIGHT * edge_score
        +
        GRADIENT_WEIGHT * gradient_score
    )

    # --------------------------------------------------------
    # NEW V5.2 neighborhood score
    # --------------------------------------------------------

    neighbor_score = neighborhood_score(
        reference,
        search,
        center_x,
        center_y
    )

    # --------------------------------------------------------
    # Final V5.2 score
    # --------------------------------------------------------

    final_score = (
        (1.0 - NEIGHBOR_WEIGHT)
        * v5_score
        +
        NEIGHBOR_WEIGHT
        * neighbor_score
    )

    return {
        "x": x,
        "y": y,
        "center_x": center_x,
        "center_y": center_y,
        "gray": gray_score,
        "edge": edge_score,
        "gradient": gradient_score,
        "v5_score": v5_score,
        "neighborhood": neighbor_score,
        "final_score": final_score
    }


# ============================================================
# MAIN V5.2 LOCALIZER
# ============================================================

def run_v5_2(
    reference_path,
    search_path
):

    reference = cv2.imread(
        reference_path,
        cv2.IMREAD_GRAYSCALE
    )

    search = cv2.imread(
        search_path,
        cv2.IMREAD_GRAYSCALE
    )

    if reference is None:

        raise FileNotFoundError(
            f"Could not read reference image: "
            f"{reference_path}"
        )

    if search is None:

        raise FileNotFoundError(
            f"Could not read search image: "
            f"{search_path}"
        )

    # ========================================================
    # TEMPLATE
    # ========================================================

    template = cv2.resize(
        reference,
        (
            TEMPLATE_SIZE,
            TEMPLATE_SIZE
        ),
        interpolation=cv2.INTER_AREA
    )

    template_edges = make_edges(
        template
    )

    template_gradient = make_gradient(
        template
    )

    # ========================================================
    # ORIGINAL V5 TEMPLATE MATCHING
    # ========================================================

    response = cv2.matchTemplate(
        search,
        template,
        cv2.TM_CCOEFF_NORMED
    )

    candidates = get_top_candidates(
        response,
        TOP_K
    )

    if len(candidates) == 0:

        raise RuntimeError(
            "No candidates found."
        )

    # ========================================================
    # EVALUATE ALL CANDIDATES
    # ========================================================

    evaluated = []

    for rank, (
        gray_score,
        x,
        y
    ) in enumerate(
        candidates,
        start=1
    ):

        result = evaluate_candidate(
            reference,
            search,
            template,
            template_edges,
            template_gradient,
            x,
            y,
            gray_score
        )

        if result is None:
            continue

        result["rank"] = rank

        evaluated.append(
            result
        )

    if not evaluated:

        raise RuntimeError(
            "Candidate evaluation failed."
        )

    # ========================================================
    # BEST CANDIDATE
    # ========================================================

    best = max(
        evaluated,
        key=lambda item:
        item["final_score"]
    )

    # Original V5 winner
    v5_best = max(
        evaluated,
        key=lambda item:
        item["v5_score"]
    )

    # ========================================================
    # OUTPUT
    # ========================================================

    print()
    print("=" * 85)
    print(
        "DRIFT-SENSE V5.2 - "
        "SPATIALLY-AWARE RERANKING"
    )
    print("=" * 85)

    print(
        f"Reference size : "
        f"{reference.shape[1]} x "
        f"{reference.shape[0]}"
    )

    print(
        f"Search size    : "
        f"{search.shape[1]} x "
        f"{search.shape[0]}"
    )

    print(
        f"Template size  : "
        f"{TEMPLATE_SIZE} x "
        f"{TEMPLATE_SIZE}"
    )

    print(
        f"Candidates     : "
        f"{len(evaluated)}"
    )

    print()

    print(
        "Rank  X       Y       "
        "V5      Neighbor  Final"
    )

    print("-" * 85)

    display_candidates = sorted(
        evaluated,
        key=lambda item:
        item["final_score"],
        reverse=True
    )

    for rank, item in enumerate(
        display_candidates[:15],
        start=1
    ):

        print(
            f"{rank:<5}"
            f"{item['center_x']:<8.2f}"
            f"{item['center_y']:<8.2f}"
            f"{item['v5_score']:<8.4f}"
            f"{item['neighborhood']:<10.4f}"
            f"{item['final_score']:.4f}"
        )

    print()
    print("=" * 85)

    print(
        "ORIGINAL V5 WINNER"
    )

    print(
        f"Center          : "
        f"({v5_best['center_x']:.2f}, "
        f"{v5_best['center_y']:.2f})"
    )

    print(
        f"V5 score        : "
        f"{v5_best['v5_score']:.4f}"
    )

    print(
        f"Neighborhood    : "
        f"{v5_best['neighborhood']:.4f}"
    )

    print()

    print(
        "V5.2 WINNER"
    )

    print(
        f"Center          : "
        f"({best['center_x']:.2f}, "
        f"{best['center_y']:.2f})"
    )

    print(
        f"V5 score        : "
        f"{best['v5_score']:.4f}"
    )

    print(
        f"Neighborhood    : "
        f"{best['neighborhood']:.4f}"
    )

    print(
        f"Final score     : "
        f"{best['final_score']:.4f}"
    )

    print("=" * 85)

    # IMPORTANT:
    # Return a dictionary so the evaluation pipeline
    # can directly consume V5.2.

    return {
        "x": best["center_x"],
        "y": best["center_y"],
        "score": best["final_score"],
        "v5_score": best["v5_score"],
        "neighborhood_score":
            best["neighborhood"],
        "v5_x": v5_best["center_x"],
        "v5_y": v5_best["center_y"],
        "v5_original_score":
            v5_best["v5_score"],
        "candidates": evaluated
    }


# ============================================================
# COMMAND LINE
# ============================================================

if __name__ == "__main__":

    if len(sys.argv) != 3:

        print(
            "Usage:"
        )

        print(
            "python "
            "localization\\baseline_v5_2.py "
            "<reference.png> "
            "<search.png>"
        )

        sys.exit(1)

    result = run_v5_2(
        sys.argv[1],
        sys.argv[2]
    )

    print()
    print(
        f"Final predicted center : "
        f"({result['x']:.2f}, "
        f"{result['y']:.2f})"
    )